### findAll users
GET http://localhost:3000/user

### findOne user
GET http://localhost:3000/user/1

### create user
POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "John Doe",
  "username": "john",
  "email": "john.doe@example.com",
  "password": "password"
}

### update user
PATCH http://localhost:3000/user/1
Content-Type: application/json

{
  "name": "Richard Roe"
}

### delete user
DELETE http://localhost:3000/user/1